; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PharmaOffice"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "D-Glopa Nigeria Limited"
#define MyAppURL "www.dglopapharamcay.com"
#define MyAppExeName "pharmaoffice.exe"

#define MyAppArchitecture
#define MySetupArchitecture
#ifdef Arch
  #if Arch == "x86_64"
    #define MyAppArchitecture "x64"
    #define MySetupArchitecture "-x64"
  #else
    #define MySetupArchitecture "-x86"
  #endif
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9B75AA34-3C7D-4C1A-BA2D-FF454DF2F588}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\ferif\OneDrive\Desktop\release\release\license.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\ferif\OneDrive\Desktop\release
OutputBaseFilename=pharmaoffice
SetupIconFile=C:\Users\ferif\OneDrive\Desktop\release\release\asserts\asserts\icons\pharmaofficeico.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
VersionInfoVersion={#MyAppVersion}
VersionInfoDescription={#MyAppName}
ArchitecturesAllowed={#MyAppArchitecture}
ArchitecturesInstallIn64BitMode={#MyAppArchitecture}
MinVersion=6.1sp1

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\base.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\boost_iostreams.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\boost_serialization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\wxbase32u_vc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\wxmsw32u_aui_vc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\wxmsw32u_core_vc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\wxmsw32u_propgrid_vc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ferif\OneDrive\Desktop\release\release\asserts\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

